### ISSUE TITLE
Cannot resolve module 'vue2-bootstrap-modal'

### ISSUE THREAD

**Issue by coolcorey** [joturako/vue2-bootstrap-modal#1]
Followed the instructions. What am I doing wrong?

ERROR in ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./src/components/reusables/signupModal.vue
Module not found: Error: Cannot resolve module 'vue2-bootstrap-modal' in /Users/corey/Desktop/slick/src/components/reusables
 @ ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./src/components/reusables/signupModal.vue 6:23-54

  components:{
    'bootstrap-modal': require('vue2-bootstrap-modal')
  },

**Comment by joturako** [comment]
It is my fault, I can't require it too. I'm fixing. Are you using webpack to process the file?

**Comment by coolcorey** [comment]
I am. For some reason, it isn't picked up in my node_modules folder.

**Comment by joturako** [comment]
It's because i have a typo in the package.json main file. Now fixed in the repo.

**Comment by coolcorey** [comment]
great! When does npm get updated with this?

**Comment by joturako** [comment]
@coolcorey I've just ```npm published``` version 0.1.1 can you please try again?
