### ISSUE TITLE
Bootstrap dialog events handlers

### ISSUE THREAD

**Issue by pdazcom** [joturako/vue2-bootstrap-modal#10]
what about events? such as `hidden.bs.modal`, `shown.bs.modal` for example. How to set a callback function on them?

thanks

**Comment by joturako** [comment]
@pdazcom I believe you can set the event like so `$("body").on('show.bs.modal',function(){})` or on the `$refs` after it's mounted

**Comment by pdazcom** [comment]
@joturako I also hoped that it would work, but for some reason it didn't. 

**i use:**

- jquery 3.1.1
- vue 2.4
- vue2-bootstrap-modal 0.1.10
- bootstrap-sass 3.3.7


**what i do:**
```
<template>
     <modal ref="modal">...</modal>
</template>

<script>
import Modal from 'vue2-bootstrap-modal'
export default {
....
        mounted() {
            console.log($(this.$refs.modal.$refs.modal))
            $(this.$refs.modal.$refs.modal).on('hidden.bs.modal', this.onClose)
        },
        methods: {
             onClose() {
                console.log('onClose event')
            },
        },
        components: {
            Modal
        }
....
}
</script>
```

modal dialog works very well, but after close i don't see any message in console

i think that these events need to be forwarded from the `Modal` component
there is example worked events https://codepen.io/anon/pen/KXMeXr?editors=1011

**Comment by joturako** [comment]
@pdazcom after checking i found out i never trigger those events, i will add `onClose` and `onOpen` so you can assign them your function like `this.$refs.modal.onOpen = ()=>{}`. Is it ok?

**Comment by joturako** [comment]
@pdazcom hi, please check the README again, i added `opened` and `closed` event and you can pass your handlers there

**Comment by pdazcom** [comment]
Yes, this partially solves the problem, but still the events `hidden.bs.modal` and `shown.bs.modal` can not be handled. And it seems to me in this case it would be better if the component firing events with `this.$emit('opened/closed')`, instead of overwriting the methods.

But in anyway, thanks for the prompt changes!

**Comment by nearia** [comment]
Is there variant to handle hide.bs.modal event?

Thanks.
