### ISSUE TITLE
Uncaught TypeError: _vm._h is not a function - vuejs 2.1.6

### ISSUE THREAD

**Issue by bigperson** [joturako/vue2-bootstrap-modal#2]
```
vue.js?3de6:523 [Vue warn]: Error when rendering component <bootstrap-modal>: 
....
vue.js?3de6:2963 Uncaught TypeError: _vm._h is not a function
```

**Comment by joturako** [comment]
I'd like to point out the ```require``` statement is used to require a `.vue` file, and you will need `vue-loader` used in the `webpack` to correctly compile it.

I used `.vue` file in `Laravel` and it use `webpack `and `vue-loader`

Can you provide more details? Vue version? Build system? 

Also read [this](https://vuejs.org/v2/guide/installation.html#Standalone-vs-Runtime-only-Build) and [this](https://github.com/ElemeFE/element/issues/1725).

**Comment by ndr** [comment]
@joturako The same issue:
vue.common.js?e881:521 [Vue warn]: Error when rendering component <modal>: 
warn @ vue.common.js?e881:521
Vue._render @ vue.common.js?e881:2223
updateComponent @ vue.common.js?e881:2609
get @ vue.common.js?e881:2934
Watcher @ vue.common.js?e881:2926
Vue._mount @ vue.common.js?e881:2608
Vue$3.$mount @ vue.common.js?e881:6178
Vue$3.$mount @ vue.common.js?e881:8549
init @ vue.common.js?e881:1740
createComponent @ vue.common.js?e881:4174
createElm @ vue.common.js?e881:4117
createChildren @ vue.common.js?e881:4242
createElm @ vue.common.js?e881:4150
patch @ vue.common.js?e881:4569
Vue._update @ vue.common.js?e881:2635
updateComponent @ vue.common.js?e881:2609
get @ vue.common.js?e881:2934
Watcher @ vue.common.js?e881:2926
Vue._mount @ vue.common.js?e881:2608
Vue$3.$mount @ vue.common.js?e881:6178
Vue$3.$mount @ vue.common.js?e881:8549
init @ vue.common.js?e881:1740
createComponent @ vue.common.js?e881:4174
createElm @ vue.common.js?e881:4117
createChildren @ vue.common.js?e881:4242
createElm @ vue.common.js?e881:4150
createChildren @ vue.common.js?e881:4242
createElm @ vue.common.js?e881:4150
patch @ vue.common.js?e881:4569
Vue._update @ vue.common.js?e881:2635
updateComponent @ vue.common.js?e881:2609
get @ vue.common.js?e881:2934
Watcher @ vue.common.js?e881:2926
Vue._mount @ vue.common.js?e881:2608
Vue$3.$mount @ vue.common.js?e881:6178
Vue$3.$mount @ vue.common.js?e881:8549
init @ vue.common.js?e881:1740
createComponent @ vue.common.js?e881:4174
createElm @ vue.common.js?e881:4117
patch @ vue.common.js?e881:4605
Vue._update @ vue.common.js?e881:2635
updateComponent @ vue.common.js?e881:2609
get @ vue.common.js?e881:2934
Watcher @ vue.common.js?e881:2926
Vue._mount @ vue.common.js?e881:2608
Vue$3.$mount @ vue.common.js?e881:6178
Vue$3.$mount @ vue.common.js?e881:8549
Vue._init @ vue.common.js?e881:3381
Vue$3 @ vue.common.js?e881:3429
(anonymous) @ main.js?3479:43
(anonymous) @ app.js:930
__webpack_require__ @ app.js:556
fn @ app.js:87
(anonymous) @ app.js:587
__webpack_require__ @ app.js:556
(anonymous) @ app.js:579
(anonymous) @ app.js:582
vue.common.js?e881:2225 Uncaught TypeError: _vm._h is not a function
    at Proxy.render (eval at <anonymous> (app.js:1434), <anonymous>:558:12)
    at VueComponent.Vue._render (eval at <anonymous> (app.js:630), <anonymous>:2216:22)
    at VueComponent.updateComponent (eval at <anonymous> (app.js:630), <anonymous>:2609:21)
    at Watcher.get (eval at <anonymous> (app.js:630), <anonymous>:2934:27)
    at new Watcher (eval at <anonymous> (app.js:630), <anonymous>:2926:12)
    at VueComponent.Vue._mount (eval at <anonymous> (app.js:630), <anonymous>:2608:19)
    at VueComponent.Vue$3.$mount (eval at <anonymous> (app.js:630), <anonymous>:6178:15)
    at VueComponent.Vue$3.$mount (eval at <anonymous> (app.js:630), <anonymous>:8549:16)
    at init (eval at <anonymous> (app.js:630), <anonymous>:1740:11)
    at createComponent (eval at <anonymous> (app.js:630), <anonymous>:4174:9)

**Comment by joturako** [comment]
@ndr please check my previous comment, make sure you use the correct vue file.

**Comment by ndr** [comment]
@joturako I am not sure what does "correct vue file" mean, maybe it will be helpful for you (found the comment on Element FE issue):
I found this commit1 in Vue which renamed _h to _c, I assume this has something to do with the problem.

But this is not to be considered a breaking change because _h it is not a public API, so 3rd-party plugins/components should not rely on it. If element-ui (and/or others) rely on this internal API, they have to fix it.

**Comment by joturako** [comment]
@ndr That was something new, I will now try to reproduce the bug. Thanks!

**Comment by joturako** [comment]
@ndr Hi, can you try again? I excluded bootstrap related css, you will need to require bootstrap-loader to load bootstrap styles. See the example ``index.html``
