### ISSUE TITLE
full size modal

### ISSUE THREAD

**Issue by SergeyMiracle** [joturako/vue2-bootstrap-modal#8]
As i see there is no way for now to make full width modal?
Can you add this feature?

**Comment by joturako** [comment]
@SergeyMiracle Hi there, could you tell me more about that? What are you putting in the modal?

**Comment by SergeyMiracle** [comment]
You have only 3 sizes, and no support for full width. I made a PR.

**Comment by joturako** [comment]
@SergeyMiracle thanks, I'm going to check the PR now.

**Comment by joturako** [comment]
@SergeyMiracle hi, i just merged your PR and publish on npm `0.1.11`, please check if it is good for you.

**Comment by SergeyMiracle** [comment]
Nice, works good. Thx.
